dist: trusty
sudo: false
language: python
python:
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphviz
install:
  - pip install -r requirements.txt
script:
 - py.test
